### ISSUE TITLE
man pages documenting data sets

### ISSUE THREAD

**Issue by Helmut01** [Helmut01/replicateBE#1]
data(package="replicateBE") does not show the items.

help(data) leads to utils.

help(package="replicateBE") does not show data, only the designs. Clicking on one of them opens the man page for data. Needs to scroll down to the See Also section. Then the desired detailed man page opens.

**Comment by Detlew** [comment]
What do you expect for paragraph 1?

Paragraph 2 is the correct behavior I think.

 What do you expect for paragraph 3?

**Comment by Helmut01** [comment]
1. `ds <- data(package="replicateBE")`
`ds # OK, but`
`ds$Item`
When I had man-pages for the individual data sets, `ds$Item` gave the description
2. OK, but why - although I have a data.Rd the man-page does not show up?
3. I see links to the the designs. When I click on them I end up at the man page `data`. But I want to navigate directly to the man page `RTRT.TRTR`.

**Comment by Detlew** [comment]
1. Duno
2. The \name{} entry in man pages is not used for getting help. For that aim the \alias{} are responsible.
\name{} is on the other hand shown on the man page, left upper corner.
3. See 2. The aliase in data.Rd are guilty

Will try to resolve.

**Comment by Helmut01** [comment]
Now all data sets have an attribute (the MD5 not needed any more). Warnings about undocumented objects in build. Had to introduce aliases. Try: `data(package="replicateBE")`.
