### ISSUE TITLE
read_excel update and additional output

### ISSUE THREAD

**Issue by mittyright** [Helmut01/replicateBE#2]
in the recent read_excel package update the authors changed the logic of new tibble created when col_names=FALSE specified
See for example here
https://stackoverflow.com/questions/55197302/new-names-18-message-in-r-console
as a result an unintended output is shown in console
New names:
_* `` -> ...1
* `` -> ...2
* `` -> ...3
* `` -> ...4
* `` -> ...5_

**Comment by mittyright** [comment]
to avoid this we need to specify additional argument for read_excel function
datawithdescr <- as.data.frame(read_excel(path = full.name, 
        sheet = set, na = c("NA", "ND", ".", "", "Missing"), 
        skip = 0, col_names = FALSE, .name_repair = 'minimal'))
so there will be no 'guess' for the names

**Comment by Helmut01** [comment]
Hi Michael, 

I will check that. In today’s release I used `suppressMessages(as.data.frame(read_excel(...)))`. Your’s looks better.

**Comment by Helmut01** [comment]
Hi Michael,
THX! Tested with Excel-file both with and wo headers.
