### ISSUE TITLE
run with R dataset

### ISSUE THREAD

**Issue by mittyright** [Helmut01/replicateBE#4]
we are providing 2 options for method.A and method.B: to import files with data or to use internal rds files. By the way there's no way to analyze the dataset which is already loaded into R

**Comment by mittyright** [comment]
possible place to add:
info.data() function

**Comment by Helmut01** [comment]
Hi Michael,

not sure whether I understand what you mean. All internal reference datasets are loaded together with the package. Do you mean that _after_ calling method.A(..., data=rds01) it should be possible to call `method.B()` but without `data=rds01`? I.e., when calling a new method, the last dataset is used?

**Comment by mittyright** [comment]
Hi Helmut,
suppose I simulated the dataset and want to get the results for that
that's a cumbersome solution to export it before method.A/B run

**Comment by Helmut01** [comment]
Hi Michael,
OK, got it. There are many problems. `info.data()` provides the description of internal datasets. I would not touch it. Possibly you try something along these lines (untested):
`nsims <- 100`
`res <- data.frame(sim = 1:nims, L = NA, U = NA, CL.lo = NA, CL.hi = NA,`
`CI = NA, GMR = NA, BE = NA, stringsAsFactors = FALSE)`
`for (i in 1:nsims) {`
`  # your simulation code`
`  rds01 <- your.data`
`  res[i, 2:8] <- method.B(data = rds01, print = FALSE, details = TRUE)[, 15:22]`
`}`
